# Generated by Django 5.0.2 on 2024-03-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_image_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
