# Generated by Django 5.0.2 on 2024-03-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_user_img_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/media//network/postImage/default-placeholder.jpg', upload_to='network/postImage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='/media/network/userImages/default_user.png', upload_to='network/userImages'),
        ),
    ]
